# Generated by Django 4.2.7 on 2023-11-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profilebio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_description', models.TextField(blank=True)),
                ('resume', models.ImageField(upload_to='product')),
                ('bio_pic', models.ImageField(blank=True, null=True, upload_to='user_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
