# Generated by Django 4.2.7 on 2023-11-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_profilebio_remove_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebio',
            name='resume',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
