# Generated by Django 4.2.7 on 2023-11-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_contact_email_contact_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilebio',
            name='bio_pic',
        ),
        migrations.RemoveField(
            model_name='profilebio',
            name='user_description',
        ),
        migrations.RemoveField(
            model_name='profilebio',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
