# Generated by Django 4.2.7 on 2023-11-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_product_image_delete_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebio',
            name='resume',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
