# Generated by Django 4.2.7 on 2023-11-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_profilebio_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profilebio',
        ),
        migrations.AddField(
            model_name='product',
            name='resume',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
